
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ranbeerchaudhary
  password: 123456789
  # host: localhost
  host: <%= ENV[ 'POSTGRES HOST' ] %>

development:
  <<: *default
  database: treelink_development
  username: ranbeerchaudhary
  password: 123456789

test:
  <<: *default
  database: treelink_test
  username: ranbeerchaudhary
  password: 123456789
#
production:
  <<: *default
  database: treelink_production
  username: ranbeerchaudhary
  password: <%= ENV["TREELINK_DATABASE_PASSWORD"] %>
