
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV[ 'POSTGRES HOST' ] %› 
  port: 5432

development:
  <<: *default
  database: treelink_development
  username: <%= ENV[ 'POSTGRES _USER'] %› 
  password: <%= ENV[ 'POSTGRES_PASSWORD'] %>


test:
  <<: *default
  database: treelink_test
  username: <%= ENV[ 'POSTGRES _USER'] %› 
  password: <%= ENV[ 'POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: ‹%= ENV[ 'POSTGRES DB'1 %›
  username: <%= ENV[ 'POSTGRES _USER'] %› 
  password: <%= ENV[ 'POSTGRES_PASSWORD'] %>
